blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://issue-helper.idux.site
    about: The issue which is not created via https://issue-helper.idux.site will be closed immediately.