// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    En: typeof import('./src/components/En.vue')['default']
    IntroEn: typeof import('./src/components/intro-en.vue')['default']
    IntroZh: typeof import('./src/components/intro-zh.vue')['default']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxCol: typeof import('@idux/components/grid')['IxCol']
    IxForm: typeof import('@idux/components/form')['IxForm']
    IxFormItem: typeof import('@idux/components/form')['IxFormItem']
    IxIcon: typeof import('@idux/components/icon')['IxIcon']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxLayout: typeof import('@idux/components/layout')['IxLayout']
    IxLayoutContent: typeof import('@idux/components/layout')['IxLayoutContent']
    IxLayoutFooter: typeof import('@idux/components/layout')['IxLayoutFooter']
    IxLayoutHeader: typeof import('@idux/components/layout')['IxLayoutHeader']
    IxMessageProvider: typeof import('@idux/components/message')['IxMessageProvider']
    IxModal: typeof import('@idux/components/modal')['IxModal']
    IxModalProvider: typeof import('@idux/components/modal')['IxModalProvider']
    IxRadioGroup: typeof import('@idux/components/radio')['IxRadioGroup']
    IxRow: typeof import('@idux/components/grid')['IxRow']
    IxSelect: typeof import('@idux/components/select')['IxSelect']
    IxTextarea: typeof import('@idux/components/textarea')['IxTextarea']
    IxTooltip: typeof import('@idux/components/tooltip')['IxTooltip']
    Preview: typeof import('./src/components/Preview.vue')['default']
    ReproduceEn: typeof import('./src/components/reproduce-en.vue')['default']
    ReproduceZh: typeof import('./src/components/reproduce-zh.vue')['default']
    Zh: typeof import('./src/components/Zh.vue')['default']
  }
}

export { }
