<script setup lang="ts">
import { computed, h, provide, ref } from 'vue'
import { ModalProviderRef } from '@idux/components/modal'
import { marked } from 'marked'
import PreviewVue from './components/Preview.vue'
import { useForm } from './composables/useForm'
import { useGithubContents } from './composables/useGithubContents'
import { useLanguage } from './composables/useLanguage'
import { useSearchIssues } from './composables/useSearchIssues'
import { getBugTemplate, getFeatureTemplate } from './utils/template'
const repositories = [{ value: 'idux', label: 'idux' }]

const types = computed(() => {
  return language.value === 'zh'
    ? [
        { value: 'bug', label: '错误报告' },
        { value: 'feature', label: '功能要求' },
      ]
    : [
        { value: 'bug', label: 'Bug report' },
        { value: 'feature', label: 'Feature Request' },
      ]
})

const { language, changeLanguage } = useLanguage()
const formGroup = useForm()
const { packages, packageDirnames } = useGithubContents(
  formGroup.get('repository'),
  formGroup.get('title.package')!,
  formGroup.get('title.name')!,
)
const searchIssues = useSearchIssues(
  formGroup.get('repository'),
  formGroup.get('title.package')!,
  formGroup.get('title.name')!,
  formGroup.get('title.content')!,
)

const typeControl = formGroup.get('type')
const issueType = computed(() => typeControl.valueRef.value)

const modalProviderRef = ref<ModalProviderRef>()

const preview = () => {
  if (formGroup.invalid.value) {
    formGroup.markAsDirty()
  } else {
    const formValue = formGroup.getValue()
    const isBug = issueType.value === 'bug'
    const template = isBug ? getBugTemplate(formValue) : getFeatureTemplate(formValue)
    const isZh = language.value === 'zh'
    modalProviderRef.value!.open({
      header: isZh ? 'Issue 预览' : 'Preview Issue',
      width: 600,
      content: h(PreviewVue, { template: marked(template) }),
      okText: isZh ? '创建' : 'Create',
      onOk: () => {
        const { repository, title } = formValue
        const { package: packageName, name, content } = title

        const submitTitle = encodeURIComponent(
          `[${packageName === 'components' ? 'comp' : packageName}:${name}] ${content}`,
        )
        const submitBody =
          encodeURIComponent(`<!-- generated by idux-issue-helper:${language.value}. DO NOT REMOVE -->
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          ${template}
          `).replace(/%2B/gi, '+')
        const label = isBug ? '' : '&labels=type:feature'
        window.open(
          `https://github.com/IDuxFE/${repository}/issues/new?title=${submitTitle}&body=${submitBody}${label}`,
        )
      },
    })
  }
}

const showIntro = ref(false)
const showReprod = ref(false)

provide('appContext', {
  formGroup,
  repositories,
  searchIssues,
  types,
  packages,
  packageDirnames,
  issueType,
  preview,
  showIntro,
  showReprod,
})
</script>

<template>
  <IxMessageProvider>
    <IxModalProvider ref="modalProviderRef">
      <IxLayout>
        <IxLayoutHeader>
          <div class="header-content">
            <div class="logo">
              <img src="/logo.svg" />
              <h1>Issue Helper</h1>
            </div>
            <div class="lang-button">
              <IxButton size="sm" @click="changeLanguage()">
                {{ language === 'zh' ? 'English' : '中文' }}
              </IxButton>
            </div>
          </div>
        </IxLayoutHeader>
        <IxLayoutContent>
          <Zh v-if="language === 'zh'" />
          <En v-else />
        </IxLayoutContent>
        <IxLayoutFooter>
          Inspired by <a href="https://new-issue.vuejs.org/" target="_blank">Vue Issue Helper</a>·
          <a href="https://github.com/IDuxFE/issue-helper">Source Code</a>
        </IxLayoutFooter>
      </IxLayout>
    </IxModalProvider>
  </IxMessageProvider>
</template>
